"""Sync canonical agent + skill specs into tool-specific directories.

Canonical sources (edit these):
    agent-tooling/agents/*.md            — one file per specialist (frontmatter + body)
    agent-tooling/skills/<name>/SKILL.md — one workflow per directory

Targets (generated — do not edit by hand):
    .claude/agents/*.md
    .claude/skills/<name>/SKILL.md

Usage:
    python agent-tooling/tools/sync_agents.py          # rebuild .claude/ from canonical
    python agent-tooling/tools/sync_agents.py --check  # exit 1 if .claude/ drifts

Wire `--check` into a pre-commit hook so nobody pushes drift.
"""

from __future__ import annotations

import sys
from pathlib import Path

# This script lives at agent-tooling/tools/. The canonical agent/skill sources sit
# next to it under agent-tooling/, but the generated .claude/ tree lives at the
# repo root so Claude Code can find it — so those two roots are distinct.
TOOLING_ROOT = Path(__file__).resolve().parent.parent  # agent-tooling/
REPO_ROOT = TOOLING_ROOT.parent                        # repo root (.claude/ lives here)
CANONICAL_AGENTS = TOOLING_ROOT / "agents"
CANONICAL_SKILLS = TOOLING_ROOT / "skills"
TARGET_AGENTS = REPO_ROOT / ".claude" / "agents"
TARGET_SKILLS = REPO_ROOT / ".claude" / "skills"

BANNER_TEMPLATE = (
    "<!-- AUTOGENERATED from {source} — edit the canonical file, "
    "then run `python agent-tooling/tools/sync_agents.py`. Do not edit this copy by hand. -->\n"
)


def insert_banner(text: str, source_rel: str) -> str:
    """Insert the AUTOGENERATED banner right after the YAML frontmatter."""
    banner = BANNER_TEMPLATE.format(source=source_rel)
    if text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end != -1:
            insert_at = end + len("\n---\n")
            return text[:insert_at] + banner + text[insert_at:]
    return banner + text


def collect_pairs() -> list[tuple[Path, Path, str]]:
    """Return [(canonical_path, target_path, source_rel_for_banner), ...]."""
    pairs: list[tuple[Path, Path, str]] = []

    for src in sorted(CANONICAL_AGENTS.rglob("*.md")):
        if src.name.startswith("_"):
            continue  # templates / partials stay canonical-only
        rel = src.relative_to(CANONICAL_AGENTS)  # e.g. operations/orchestrator.md
        pairs.append((src, TARGET_AGENTS / rel, f"agent-tooling/agents/{rel.as_posix()}"))

    for src in sorted(CANONICAL_SKILLS.glob("*/SKILL.md")):
        skill_name = src.parent.name
        pairs.append(
            (
                src,
                TARGET_SKILLS / skill_name / "SKILL.md",
                f"agent-tooling/skills/{skill_name}/SKILL.md",
            )
        )

    return pairs


def existing_generated_files() -> set[Path]:
    """All .md files currently sitting in the generated tree."""
    found: set[Path] = set()
    if TARGET_AGENTS.exists():
        found.update(TARGET_AGENTS.rglob("*.md"))
    if TARGET_SKILLS.exists():
        found.update(TARGET_SKILLS.glob("*/SKILL.md"))
    return found


def write_mode() -> int:
    pairs = collect_pairs()
    expected = {target for _, target, _ in pairs}

    for src, target, source_rel in pairs:
        content = src.read_text(encoding="utf-8")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(insert_banner(content, source_rel), encoding="utf-8", newline="\n")
        print(f"wrote {target.relative_to(REPO_ROOT).as_posix()}")

    orphans = existing_generated_files() - expected
    for orphan in sorted(orphans):
        orphan.unlink()
        print(f"removed orphan {orphan.relative_to(REPO_ROOT).as_posix()}")

    return 0


def check_mode() -> int:
    pairs = collect_pairs()
    expected = {target for _, target, _ in pairs}
    problems: list[str] = []

    for src, target, source_rel in pairs:
        want = insert_banner(src.read_text(encoding="utf-8"), source_rel)
        if not target.exists():
            problems.append(f"missing: {target.relative_to(REPO_ROOT).as_posix()}")
            continue
        got = target.read_text(encoding="utf-8")
        if got != want:
            problems.append(f"drift:   {target.relative_to(REPO_ROOT).as_posix()}")

    for orphan in sorted(existing_generated_files() - expected):
        problems.append(f"orphan:  {orphan.relative_to(REPO_ROOT).as_posix()}")

    if problems:
        print("Out of sync with canonical sources:")
        for p in problems:
            print(f"  {p}")
        print("\nRun: python agent-tooling/tools/sync_agents.py")
        return 1

    print("In sync.")
    return 0


def main() -> int:
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        return check_mode()
    return write_mode()


if __name__ == "__main__":
    sys.exit(main())
